import turtle

turtle.getscreen()
turtle.width(4) 
turtle.shape("turtle")
turtle.shapesize(2,2,2)
turtle.fillcolor("green")
turtle.color("green", "yellow")
turtle.begin_fill()
turtle.fd(100)
turtle.lt(90)
turtle.fd(100)
turtle.lt(90)
turtle.fd(100)
turtle.lt(90)
turtle.fd(100)
turtle.end_fill()
